### ISSUE TITLE
Calculate "all" conditions fails with condition: '<>' when the value is NULL

### ISSUE THREAD

**Issue by philayres** [consected/restructure#180]
Since all conditions are passed directly to active query to evaluate, a condition something like:

```
  all:
    table_name:
      var:
        condition: <>
        value: 8
```

... always fails if the value is NULL. This is because the SQL evaluates to:

    select * from table_name where var <> 8;

and Postgres does not return TRUE for `NULL <> 8`

This is considered a bug, since:

1. There is no simple way to define a condition to check for NOT NULL and '<>'
2. "any" conditions are evaluated outside of the query and Ruby treats `nil != 8` as true
