### ISSUE TITLE
::general_selection_label substitution formatter not working in master_header_title app configuration

### ISSUE THREAD

**Issue by philayres** [consected/restructure#209]
`{{activity_log__project_assignments.last.status::general_selection_label}}` seems to show the value, not the label

**Comment by philayres** [comment]
Not a bug - the options were not defined for the activity log being referenced. This is needed:

```yaml
  field_options: 
    status:
      edit_as: 
        field_type: select_status
        alt_options:
          analysis project review completed - not approved: analysis project rejected

```
