### ISSUE TITLE
valid_if not working with no_masters

### ISSUE THREAD

**Issue by philayres** [consected/restructure#228]
```
      all:
        no_masters: {}
        users:
          email:
            this: email
          invalid_error_message: 'This email address does not exist as a user of Viva ROADMap'
```
