### ISSUE TITLE
Allow nfs_store configs to provide container level control of can_...?

### ISSUE THREAD

**Issue by philayres** [consected/restructure#236]
The aim is to provide more  granular control than that enforced by user access controls or container parent activity log `can_edit?`

The current list of actions that we should enforce at this level are:

- can_edit?
- can_download_or_view?
- can_download?
- can_send_to_trash?
- can_move_files?
- can_user_file_actions?

Configure with:

```yaml
  nfs_store:
    can:
      edit_if:
      download_or_view_if:
      download_if:
      view_if:
      send_to_trash_if:
      move_files_if:
      user_file_actions_if:
```

For simplicity at this stage, `user_file_actions` should be treated as they are currently, all available or all not available.
