### ISSUE TITLE
Conditions don't work correctly for nested user: role_name: 'name'

### ISSUE THREAD

**Issue by philayres** [consected/restructure#240]
Neither of the following work correctly:

```yaml
  any:
    user:
      role_name:
          - x
          - y
    any:
       this:
          id: -999
```
or

```yaml
  any:
    all:
      user:
        role_name:
          - x
          - y
    any:
       this:
          id: -999
```
