### ISSUE TITLE
create reference or update reference with embedded_item.field_name

### ISSUE THREAD

**Issue by philayres** [consected/restructure#344]
Create or update a reference with fields in a defined embedded item of the reference item.

So we may have something like:

```
  create_reference:
    - activity_log__something:
        with:
          extra_log_type: activity
          embedded_item.notes: "The notes to go into the embedded_item's notes field"  
```
