### ISSUE TITLE
Provide a batch_trigger and scheduling mechanism

### ISSUE THREAD

**Issue by philayres** [consected/restructure#36]
An admin wants to be able to schedule actions that occur once a day, at a certain time of day. These actions could be provided by something similar to the save_trigger actions in dynamic definitions, providing a series of actions to be performed against a record if certain conditions are met.

Rather than actions being triggered by saving or creating a record, a batch of records would be run through when scheduled, the existence of each record firing the trigger. Every record in the dynamic model would be tested against an "if" condition, then the following trigger actions would be run (each of these could have its own "if" conditions)

The dynamic model could be represented by a regular table, potentially populated by an external process, allowing schedule responses to be performed against externally generated data. Or a view SQL definition within a dynamic model could be used, allowing a completely dynamic batch to be defined.

The addition of the following would define the batch_trigger mechanism in a dynamic model, external identifier or activity log:

```yaml
default:
  # ...
  batch_trigger:
    - if:
        always: true # for example...
      then:
        - add_tracker:
        - notify:
        - add_tracker:
        - create_reference:
    
```

Notice the list array in "then:" block, allowing for defined ordering of actions, with the potential to repeat actions with the same name. An alternative definition might use a simple hash here if ordering is not required.

The above is perhaps idealistic. A simpler implementation would be to use an exact copy of the save_triggers:

```yaml
default:
  # ...
  batch_trigger:
    on_record:
      notify:
      add_tracker:
      create_reference:
    
```
