### ISSUE TITLE
Improve error messages if condition has `masters: {}` in wrong position or another key is an empty hash

### ISSUE THREAD

**Issue by philayres** [consected/restructure#367]
```
error: undefined method `first' for nil:NilClass
backtrace: |-
  /var/app/current/app/models/calc_actions/calculate.rb:235:in `generate_match_query_condition'
  /var/app/current/app/models/calc_actions/calculate.rb:660:in `block (2 levels) in calc_base_query'
  /var/app/current/app/models/calc_actions/calculate.rb:647:in `each'
  /var/app/current/app/models/calc_actions/calculate.rb:647:in `block in calc_base_query'
  /var/app/current/app/models/calc_actions/calculate.rb:632:in `each'
  /var/app/current/app/models/calc_actions/calculate.rb:632:in `calc_base_query'
  /var/app/current/app/models/calc_actions/calculate.rb:80:in `block (2 levels) in do_calc_action_if'
  /var/app/current/app/models/calc_actions/calculate.rb:78:in `each'
  /var/app/current/app/models/calc_actions/calculate.rb:78:in `block in do_calc_action_if'
  /var/app/current/app/models/calc_actions/calculate.rb:61:in `each'
  /var/app/current/app/models/calc_actions/calculate.rb:61:in `do_calc_action_if'
  /var/app/current/app/models/conditional_actions.rb:38:in `get_this_val'
  /var/app/current/app/models/save_triggers/update_reference.rb:62:in `block (3 levels) in perform'
  ```

**Comment by philayres** [comment]
This was due to using `masters: {}` in a condition, in the wrong place.

```
              first:
                biodata_invites:
                  masters: {}              
                  biodata_invite_ext_id:
                    this: redcap_survey_identifier
                  update: return_result
```

It should have been:

```
              first:
                masters: {}              
                biodata_invites:
                  biodata_invite_ext_id:
                    this: redcap_survey_identifier
                  update: return_result
```

We should raise an exception with a meaningful error if the hash is empty. Something like:

`A hash definition can not be empty. The key: ... is defined as an empty hash.`

For the key `masters` or `no_masters` - extend the message to say: `Maybe the <key> should be at the top level.`
