### ISSUE TITLE
Provide a template for each subsection of option configs

### ISSUE THREAD

**Issue by philayres** [consected/restructure#368]
Allow a user to add a section by clicking it from a tree (generated from detailed options YAML), such as:

```
  save_trigger:
    on_create: # run when a model is created <click this
    on_update: # run when a model is updated after initial creation
    on_save: # run when a model is created or updated
```
adds the section without comments:

```
  save_trigger:
    on_create:
```

Then for each section, such `update_reference`

```
  save_trigger:
    on_create:
      - ...
      - update_reference:
      - ...
```

Adds the update_reference template
