### ISSUE TITLE
A category of redcap dynamic models showing as a default panel loads all entries in the database

### ISSUE THREAD

**Issue by philayres** [consected/restructure#370]
Since there is no master association, all the records are loaded.

Two options: never load anything into a panel that doesn't have a master association or "foreign key name" matching to msid for example.

Or allow a foreign key to be specified as something like this in the option config:

```
_configurations:
  foreign_key_through_external_id:
    key_field: <field in this table>
    external_identifier: <external identifier resource name>
```

This then is used to handle a lookup of the master throught the external identifier.
