### ISSUE TITLE
view_options.alt_width_classes doesn't work for external ID or dynamic models displayed in master panels

### ISSUE THREAD

**Issue by philayres** [consected/restructure#389]
## Scenario

Dynamic model and external identifier options should allow the specification of alternative classes to be used, instead of the bootstrap standard `col-*-*` classes. The options are like this:

```yaml
default:
  view_options:
    alt_width_classes: col-md-18 col-lg-18 col-md-offset-3 al-shrinkable
```
When the standard master panels are displayed (for a dynamic model category or external identifiers) the option isn't applied.

## Approach

Before implementing anything, build system spec tests to verify the current implementation, especially focusing on the dynamic model orientation setting, to ensure this isn't broken in any fix. Also, the default without this setting needs to be validated to work as part of the testing.
