### ISSUE TITLE
Need a simple conditional if to match when the one of several items results in a specific value

### ISSUE THREAD

**Issue by philayres** [consected/restructure#392]
For example:

```
  activity_log__player_contacts:
    extra_log_type:
      - a
      - b
      - c
    and_latest_matches:
      extra_log_type: unlock

  # Check if the latest record matched on the previous conditions also matches the `and_latest_matches` conditions
  # This is useful for checking a list of possible extra_log_type and only matching if the latest one
  # is a specific activity. This can't be achieved through other mechanisms, such as nested conditions,
  # since they limit the results.

```
Would only evaluate to true if 'b' is the first of all records having extra_log_type as any one of a,b,c

Something like: get the results in(a,b,c) and check the first result is 'b'
