### ISSUE TITLE
Files containers are not always being created in a save trigger

### ISSUE THREAD

**Issue by philayres** [consected/restructure#482]
The Viva team has observed that files containers are not being created when a save trigger is fired when an activity is created from another trigger. This seems to be happening for a single activity type.

Configurations specific to the activity:

```
  save_trigger:
    on_save:
      create_filestore_container: 
        name: additional documentation
        label: Additional Documentation
        create_with_role: nfs_store group 600
        skip_if_exists: master
```
Maybe the `skip_if_exists` condition is not resolving correctly? 

Alternatively, there is an issue when a trigger creates a reference that then fires this trigger? Unlikely, since other activities use this approach.

```
  save_triggers:
    on_create:
      create_reference:
        - activity_log__project_assignment:
            in: this
            with:
              extra_log_type: additional_documentation
              event_date:
                this:
                  event_date: return_value
            force_create: true
            force_not_valid: true

```
