### ISSUE TITLE
Need a way to keep configurations such as save_trigger when reconfiguring Redcap dynamic model

### ISSUE THREAD

**Issue by philayres** [consected/restructure#49]

**Comment by philayres** [comment]
This can be achieved by adding a _default: section to a config library, then adding a configuration setting:

```
prefix_dynamic_model_config_library: <category> <name>
```

The library will always be added to the top of the generated dynamic model.

For example, the config library could be:

```
_default:
  save_trigger:
    on_save:
      # ... etc
```

Fixed by 7c83041a637cc2b73b29e71718dc7965e9f89dd6
