### ISSUE TITLE
Allow secrets to be stored / retrieved and used in substitutions (for pull_external_data)

### ISSUE THREAD

**Issue by philayres** [consected/restructure#55]
For example, APIs will want to use things like '&client_secret=<some secret>'  in a URL or header.

Prefer an approach that does not require rebuilding the app, or using ENV variables (as AWS limits space on these).

Consider a pluggable approach with one plugin that gets secrets from AWS secrets manager, on demand and cached.

**Comment by philayres** [comment]
Handled by PR #967 

## Step-by-Step

Create a new dynamic model with:

- table name: `api_secrets`
- primary key name: `id`
- field list: `name category secret disabled`

Add options:

```yaml
_db_columns:
  secret:
    type: string
    encrypted: true

default:
  field_options:
    secret:
      no_downcase: true
      view_original_case: true
```

Enter a secret by searching the table and adding an entry. For this example, use name `marketo_client_secret` and category `marketo`.

In a dynamic model or config library, use the new secret by setting a variable, for example:

```yaml
    set_variables:
      - name: marketo_client_secret
        value:
          no_masters: {}
          dynamic_model__api_secrets:
            disabled:
              - null
              - false
            category: marketo
            name: marketo_client_secret
            secret: return_value
```

Then use the variable wherever needed with `{{variables.marketo_client_secret}}`
