### ISSUE TITLE
Phone contacts rank filter buttons - need an app config for which to show as active

### ISSUE THREAD

**Issue by philayres** [consected/restructure#584]
## Requirement 1

In `app/views/masters/_search_results_parts.html.erb`

Line 176 enables the buttons:

```
<button class="btn btn-default btn-sm filter-switch {{#if ../all_active}}active{{else}}{{#is @key 0}}active{{/is}}{{/if}}" 
```
Provide an page layout master tab setting that allows named models to set the sub list items to make active by default (or 'all' to set the `all_active` attribute)

For example, a config like:

```
view_options:
  active_sublist_values:
    player_contacts: [10,5] # array of values
    addresses: all # string "all" indicates all values
    dynamic_model__other_contacts: [] # indicates no values
    # If a key isn't present, it should use the current default 
```

`{{>sublist_controls ...` handlebars call to partial needs to be updated in `_dynamic_master_blocks.html.erb` and `_master_panels.html.erb`

## Requirement 2

Provide a similar setting to set the default for the "reverse sorting" button, to set the default value for `data-order-val` attribute.

```
view_options:
  sort_sublists:
    player_contacts: asc
    addresses: desc
```
