### ISSUE TITLE
Add full text search to Postgres

### ISSUE THREAD

**Issue by philayres** [consected/restructure#74]
## Requirement 1

After upload of a configured filestore document (in a delayed job), send the content of the document (rendered to raw text, or its previously extraced OCR content) to a dynamic model table / field specifically for full text search indexing. To enable this, the `nfs_store` configuration should include an option for the target dynamic model resouce name and field name. If not specified, don't store any content to the database.

## Requirement 2

A dynamic definition should have a configuration to save a set of fields to another table or the current table to be indexed for full text search.

## Common Options

An option common to both `nfs_store` and the dynamic definition options might be:

```
  full_text_search:
    target_table: a_table
    target_field: a_tsvector_field
    with_fields:
      - title
      - subtitle
      - body
      - extracted_file_text_content ## to include the an filestore uploaded document's raw content
```
NOTE: for the filestore document content, include the field name `extracted_file_text_content` to indicate the raw text content extracted from the uploaded file.

The target table should already have a tsvector type column added. One approach is:

```
ALTER TABLE tablename
    ADD COLUMN textsearchable_index_col tsvector
               GENERATED ALWAYS AS (to_tsvector('english', coalesce(title, '') || ' ' || coalesce(body, ''))) STORED;

CREATE INDEX textsearch_idx ON tablename USING GIN (textsearchable_index_col);
```

## Notes

A report can simply include standard SQL to search the full text field, without any changes to implementation:

```
SELECT title
FROM pgweb
WHERE textsearchable_index_col @@ to_tsquery('create & table')
ORDER BY last_mod_date DESC
LIMIT 10;
```
